### ISSUE TITLE
ActionView::MissingTemplate (Missing template sequences/update.erb 

### ISSUE THREAD

**Issue by scottmessinger** [rubymood/jintastic#1]
When I use jintastic, I get the following error: 

ActionView::MissingTemplate (Missing template sequences/update.erb in view path app/views:vendor/plugins/typus/app/views:/Users/ScottMessinger/.gem/ruby/1.8/gems/declarative_authorization-0.4/app/views):
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/legacy/respond_to.rb:107:in `retrieve_response_from_mimes'
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/legacy/responder.rb:163:in`call'
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/legacy/responder.rb:163:in `default_render'
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/legacy/responder.rb:129:in`to_format'
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/legacy/responder.rb:106:in `call'
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/legacy/respond_to.rb:65:in`respond_with'
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/base_helpers.rb:306:in `respond_with_dual_blocks'
  /Users/ScottMessinger/.gem/ruby/1.8/gems/josevalim-inherited_resources-0.9.1/lib/inherited_resources/actions.rb:51:in`update'
  haml (2.2.17) lib/sass/plugin/rails.rb:19:in `process'

Why is this?

**Comment by rubymood** [comment]
With jintastic you modify your sequence resource, so you need an update view like this in sequences/update.js.erb for your respond:

```
$('#<%= dom_id @sequence %>').replaceWith('<%= escape_javascript render @sequence %>')
```
